### ISSUE TITLE
26 - As a student, I want to edit a review so that I can change its information

### ISSUE THREAD

**Issue by ChenFangFangFang** [unicornteam2024/quizzer#107]

**Comment by emaDBytes** [comment]
## Backend Tasks:

1. Implement PUT /api/reviews/{id} endpoint

- Create ReviewUpdateDTO to validate request body (should include reviewerNickname, rating, and reviewText)
- Implement endpoint to update an existing review
- Add validation to ensure rating is between 1-5
- Add error handling for non-existent reviews
- Add validation to ensure review text is not empty
- Add appropriate HTTP status codes (200 for success, 404 for not found, 400 for invalid input)


2. Implement tests for review update endpoint

- Test successful review update
- Test updating non-existent review
- Test validation of rating range
- Test validation of required fields
- Test error handling



## Frontend Tasks:

1. Create EditReview component

- Create form with fields for nickname, rating, and review text
- Pre-populate form with existing review data
- Add validation for rating (1-5)
- Add validation for required fields
- Style the form using Tailwind CSS
- Add submit button


2. Implement review update functionality

- Create updateReview service function to call the API
- Add form submission handler
- Add error handling for API calls
- Show loading state during submission
- Show success/error messages to user


3. Update ReviewsList component

- Add edit button next to each review
- Add logic to show edit form when edit button is clicked
- Handle state updates after successful edit
- Add confirmation message after successful edit
- 

4. Add navigation

- Implement "Cancel" functionality to return to reviews list
- Handle routing/navigation after successful update


5. Implement UI feedback

- Add loading indicators during API calls
- Show success message after successful update
- Show error messages if update fails
- Add confirmation before canceling edits



The Scrum Team's UI Designer's vision for the edit review form could look something like this:
Copy[Review for: Quiz Name]

Nickname: [Input field]
Rating: [Select 1-5]
Your Review: [Text area]

[Update Review] [Cancel]
