### ISSUE TITLE
36 - Create GitHub release Sprint 3 for the project at the end of Sprint 3 (Exercise 18)

### ISSUE THREAD

**Issue by chloee122** [unicornteam2024/quizzer#127]

**Comment by emaDBytes** [comment]
# Create GitHub release for Sprint 3

Create the final release for Sprint 3 after all work is completed.

## Tasks
1. Verify all Sprint 3 user stories and tasks are completed:
   - Review functionality
   - Testing implementation
   - Documentation updates
   - Bug fixes

2. Ensure main branch has working version:
   - Backend works
   - Frontend works
   - All features are functional
   - Documentation is up to date

3. Create GitHub release:
   - Create new tag "sprint3"
   - Set release title as "Sprint 3"
   - Write comprehensive release description

## Release Description Should Include
- Summary of new features implemented
- List of major bug fixes
- Documentation updates
- Testing improvements
- Any breaking changes
- Deployment updates

## Acceptance Criteria
- All Sprint 3 work is completed and verified
- Release is properly tagged as "sprint3"
- Release description is comprehensive and clear
- Release is properly linked to the milestone
- Code is in a stable, working state

## Notes
This is one of the final tasks of Sprint 3, done only after all other work is completed and verified.
