### ISSUE TITLE
20 - As a user, I want to see the number of correct and wrong answers of each question of a quiz so that I can know the results of a quiz

### ISSUE THREAD

**Issue by chloee122** [unicornteam2024/quizzer#63]

**Comment by emaDBytes** [comment]
Description:
Results page should show:

Difficulty level of each question
Total number of answers for each question
Number of correct and wrong answers per question
Correct answer percentage
Overall quiz statistics (total questions and answers)
Link to results page should be available next to quiz in list

Labels: user story, frontend
Milestone: Sprint 2

**Comment by emaDBytes** [comment]
User story #63 is now complete with working statistics and proper answer feedback.

Current status:
✅ Service layer (#93)
✅ Results page component (#94) 
✅ Results link in quiz list (#95)
