### ISSUE TITLE
17 - As a student, I want to see a list of published quizzes so that I know which quizzes I can take

### ISSUE THREAD

**Issue by chloee122** [unicornteam2024/quizzer#65]

**Comment by emaDBytes** [comment]
Description:
When a student takes a quiz:
- Questions should be listed on the quiz page
- Student should be able to choose an answer option for each question
- Student should be able to submit their answer
- After submission, a feedback dialog should show if the answer was correct
- Feedback messages like "That is correct, good job!" or "That is not correct, try again"

Labels: user story, frontend
Milestone: Sprint 2

**Comment by emaDBytes** [comment]
Backend Issues Missing!
Suggestions for Backend Implementation: Quiz Questions and Answers Management
Description:
Backend requirements for quiz-taking functionality:
- Adding questions and answers through teacher dashboard
- API endpoints for:
  * Getting quiz questions
  * Getting question answers
  * Submitting answers
  * Validating answers
This will allow removal of mockQuizData.js and updating quizService.js to use real endpoints.

**Comment by emaDBytes** [comment]
I successfully replaced the mock data with real API calls and confirmed it's working
